# LFM梯度下降

In [1]:
import numpy as np
import pandas as pd

In [10]:
#生成评分数据
R = np.array([[4,0,2,0,1],[2,5,2,1,1],[2,0,2,2,1],[2,5,2,1,1],[5,0,2,0,1],[4,1,2,2,1]])
R.shape
pd.DataFrame(R)

   0  1  2  3  4
0  4  0  2  0  1
1  2  5  2  1  1
2  2  0  2  2  1
3  2  5  2  1  1
4  5  0  2  0  1
5  4  1  2  2  1

In [11]:
#算法
K = 5 #因特征维度
max_iter = 10000 #迭代次数
alpha = 0.0001
lamda = 0.004 #正则项系数

def LFM_grad_desc(R,K,max_iter, alpha,lamda):
    M = len(R)
    N = len(R[0])
    
    P = np.random.rand(M,K)
    Q = np.random.rand(N,K)
    Q = Q.T
    
    for step in range(max_iter):
        for u in range(M): #用户u
            for i in range(N): #物品i
                if R[u][i]>0:
                    err_ui = np.dot(P[u,:],Q[:,i]) - R[u][i]
                    #公式
                    for k in range(K):
                        P[u][k] -= alpha * (err_ui * 2 * Q[k][i] + 2 * lamda * P[u][k])
                        Q[k][i] -= alpha * (err_ui * 2 * P[u][k] + 2 * lamda * Q[k][i])
        #更新完成
        predR=np.dot(P,Q)
        
        cost = 0
        for u in range(M):
            for i in range(N):
                if R[u][i]>0:
                    #累计损失
                    cost+=(np.dot(P[u,:],Q[:,i]) - R[u][i])**2
                    #计算正则
                    for k in range(K):
                        cost +=lamda * (P[u][k]**2+Q[k][i]**2)
        #print("setp:",step)
        # print("cost:",cost)
        if cost<0.001:
            break
    return P,Q.T,cost

In [14]:
#测试
P,Q,cost = LFM_grad_desc(R,K,max_iter, alpha,lamda)

print(P)
print(Q)
print(cost)

predR = P.dot(Q.T)
print(R)
pd.DataFrame(predR)

[[ 1.01525     1.31394476  0.50656478  0.79722938  0.59362474]
 [ 1.21836504  0.2830329  -0.07767953  1.30292912  0.47823294]
 [ 1.11240962  0.29222638  0.08878244  0.53350597  1.14012859]
 [ 1.08822266  0.49033073 -0.33699848  1.10003253  0.80017705]
 [ 0.79601236  1.59191922  0.73956785  1.00477242  0.65248008]
 [-0.03564737  0.5355083   1.52465849  0.47227405  0.98161787]]
[[ 0.23987956  1.53707083  1.40001596  0.81082437  0.68144495]
 [ 1.81597225  0.91578721 -0.57476201  1.64888347  0.7010562 ]
 [ 0.46981045  0.12043072  0.36300979  0.63524509  1.0221943 ]
 [ 0.58174615  0.23412914  0.74396289 -0.03391628  0.84646065]
 [ 0.61870332 -0.09683997  0.44245605  0.13190827  0.31018747]]
0.8789121443173742
[[4 0 2 0 1]
 [2 5 2 1 1]
 [2 0 2 2 1]
 [2 5 2 1 1]
 [5 0 2 0 1]
 [4 1 2 2 1]]

          0         1         2         3         4
0  4.023298  4.486508  1.932338  1.750557  1.014325
1  2.000886  5.000009  1.894814  1.077870  1.012237
2  2.049828  3.915677  2.094384  1.728589  1.123262
3  1.980122  4.993709  1.964702  1.137165  0.870005
4  4.932570  4.592498  2.139399  1.904223  1.000489
5  4.000959  1.016255  1.904624  2.053813  0.967463